// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Duck of Power":return img`
....................
..............99....
............999f....
.........9999ff.....
........99ffffff....
.......9fff11fff....
.......ffff11ff3....
......fffffffff33...
...ffffdfffff33333..
..ffddd11dff33333...
..ffddfff1fffffff...
..ffddffff1fff......
..fffdddffdfff......
...ffddddddfff......
....fffdddddff......
.....ffffffff.......
.....f.....f........
.....f.....f........
.....fff...fff......
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
